[package]
name = "untitled13"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
container = {path = "base/container"}
model = {path = "base/model"}
threadpool = {path = "base/threadpool"}